# Generated by Django 2.2.12 on 2021-03-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('F', 'foot'), ('C', 'car'), ('B', 'bike')], max_length=4)),
            ],
        ),
    ]
