# Generated by Django 2.2.12 on 2021-03-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_courier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
