# Generated by Django 2.2.12 on 2021-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_courier_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkingHours',
            new_name='Hours',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_hours',
            field=models.ManyToManyField(to='myapp.Hours'),
        ),
    ]
