# Generated by Django 2.2.12 on 2021-03-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210325_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours',
            new_name='HoursInterval',
        ),
    ]
