# Generated by Django 2.2.12 on 2021-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210325_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[(10, 'foot'), (50, 'car'), (15, 'bike')], max_length=4),
        ),
    ]
