# Generated by Django 2.2.12 on 2021-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210325_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('F', 'foot'), ('C', 'car'), ('B', 'bike')], max_length=4),
        ),
    ]
