# Generated by Django 2.2.12 on 2021-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210325_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(default=None),
        ),
    ]
