# Generated by Django 2.2.12 on 2021-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210325_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
