# Generated by Django 2.2.12 on 2021-03-26 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=None, size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_hours',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=None, size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HoursInterval',
        ),
    ]
