# Generated by Django 2.2.12 on 2021-03-26 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210326_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
