# Generated by Django 2.2.12 on 2021-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210326_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
