# Generated by Django 2.2.12 on 2021-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_order_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('foot', 'foot'), ('car', 'car'), ('bike', 'bike')], max_length=4),
        ),
    ]
