# Generated by Django 2.2.12 on 2021-03-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210327_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='orders',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Order'),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
