# Generated by Django 2.2.12 on 2021-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210328_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='weight_remained',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
