# Generated by Django 2.2.12 on 2021-03-28 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210328_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='weight_remained',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
