# Generated by Django 2.2.12 on 2021-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210328_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
